# --- Application settings ---
replicaCount: 2

image:
  repository: uzayrq/flask
  tag: "latest"
  pullPolicy: IfNotPresent

app:
  port: 5000
  title: "Random Facts API"
  language: "en"

service:
  type: ClusterIP
  port: 80

# --- Resources ---
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

# --- Probes ---
readinessProbe:
  path: /healthz
  port: 5000
  initialDelaySeconds: 2
  periodSeconds: 10

livenessProbe:
  path: /failcheck
  port: 5000
  initialDelaySeconds: 5
  periodSeconds: 20

# --- Autoscaling ---
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

# --- Network Policy ---
networkPolicy:
  enabled: false
  allowedNamespaces:
    - ingress-namespace
  allowedPods:
    - app: nginx-ingress
