apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flask-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-flask
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-flask
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
