---
apiVersion: v1
kind: Namespace
metadata:
  name: flask-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer
  namespace: flask-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: flask-app
  name: deployer-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources:
      [
        "pods",
        "pods/log",
        "services",
        "configmaps",
        "secrets",
        "persistentvolumeclaims",
      ]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-binding
  namespace: flask-app
subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: flask-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployer-role
