persistence:
  enabled: true
  storageClass: "local-storage"
  size: 2Gi

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

elasticsearch:
  hosts:
    - elasticsearch
  port: 9200
  security:
    auth:
      enabled: true
      existingSecret: "kibana-secret"
      elasticsearchPasswordSecret: "elasticsearch-secret"
    tls:
      enabled: true
      verificationMode: "full"
      existingSecret: "elasticsearch-master-crt"
      usePemCerts: true

extraConfiguration:
  xpack.fleet.enabled: false
  telemetry.enabled: false

readinessProbe:
  enabled: true
  initialDelaySeconds: 300
  timeoutSeconds: 10
  periodSeconds: 15
  failureThreshold: 10
