rbac:
  create: true
serviceAccount:
  create: true

extraVolumes:
  - name: es-ca
    secret:
      secretName: elasticsearch-master-crt

extraVolumeMounts:
  - name: es-ca
    mountPath: /fluent-bit/certs/ca.crt
    subPath: ca.crt
    readOnly: true

extraEnvVarsSecret: "elasticsearch-secret"

daemonset:
  enabled: true
  podSecurityContext:
    enabled: true

# Needed because we need to read /var/logs/contianers which can't be done by regular user
containerSecurityContext:
  enabled: true
  privileged: true
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: true

config:
  customParsers: |
    [PARSER]
        Name     flask_json
        Format   json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L

  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Tag kube.*
        Parser docker
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

  filters: |
    [FILTER]
        Name            kubernetes
        Match           kube.*
        Kube_URL        https://kubernetes.default.svc:443
        Kube_CA_File    /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log       Off
        Keep_Log        On

  outputs: |
    [OUTPUT]
        Name             es
        Match            *
        Host             elasticsearch.logging.svc.cluster.local
        Port             9200
        HTTP_User        elastic
        HTTP_Passwd      password123
        Logstash_Format  On
        Logstash_Prefix  kube
        Suppress_Type_Name On
        # Secure TLS Configuration
        tls              On
        tls.verify       On
        tls.ca_file      /fluent-bit/certs/ca.crt
