name: Push to Registry

on:
  push:
    branches: ["main"]

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        run: |
          IMAGE=myapp:${{ github.sha }}
          docker build -t $IMAGE .
          docker tag $IMAGE mydockerhubuser/myapp:${{ github.sha }}
          docker push mydockerhubuser/myapp:${{ github.sha }}
