# name: Helm Deploy

# on:
#   workflow_dispatch: # run manually after push

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Setup kubectl
#         uses: azure/setup-kubectl@v4
#         with:
#           version: v1.29.0

#       - name: Setup Helm
#         uses: azure/setup-helm@v4
#         with:
#           version: v3.14.0

#       - name: Configure Kube Context
#         run: |
#           echo "${{ secrets.KUBECONFIG_FILE }}" > kubeconfig.yaml
#           export KUBECONFIG=kubeconfig.yaml

#       - name: Helm Upgrade
#         run: |
#           helm upgrade --install myapp ./helm \
#             --set image.repository=mydockerhubuser/myapp \
#             --set image.tag=${{ github.sha }}
